import type { Vehicle, Alert, ServiceHistory, Notification, User } from './types'

export const mockUsers: User[] = [
  {
    id: '1',
    name: 'Carlos Mendez',
    email: 'carlos@transportesmendez.com',
    role: 'client',
    company: 'Transportes Mendez S.A.',
  },
  {
    id: '2',
    name: 'Miguel Torres',
    email: 'miguel@tallerautocam.com',
    role: 'workshop',
    company: 'Taller AutoCam',
  },
  {
    id: '3',
    name: 'Roberto Sanchez',
    email: 'roberto@transportesmendez.com',
    role: 'driver',
  },
  {
    id: '4',
    name: 'Admin Sistema',
    email: 'admin@autocam.com',
    role: 'admin',
  },
]

export const mockVehicles: Vehicle[] = [
  {
    id: '1',
    plate: 'AB 123 CD',
    brand: 'Mercedes-Benz',
    model: 'Actros 2546',
    year: 2021,
    status: 'operational',
    health: 92,
    lastService: '2025-12-15',
    nextService: '2026-03-15',
    mileage: 145000,
    driver: 'Roberto Sanchez',
    alerts: [],
    image: '/trucks/truck-1.jpg',
  },
  {
    id: '2',
    plate: 'EF 456 GH',
    brand: 'Scania',
    model: 'R500',
    year: 2020,
    status: 'attention',
    health: 68,
    lastService: '2025-11-20',
    nextService: '2026-02-20',
    mileage: 198000,
    driver: 'Juan Perez',
    alerts: [
      {
        id: 'a1',
        vehicleId: '2',
        type: 'Frenos',
        message: 'Desgaste de pastillas detectado - 30% restante',
        severity: 'medium',
        timestamp: '2026-01-28T10:30:00',
        isRead: false,
      },
    ],
  },
  {
    id: '3',
    plate: 'IJ 789 KL',
    brand: 'Volvo',
    model: 'FH16 750',
    year: 2019,
    status: 'critical',
    health: 35,
    lastService: '2025-10-05',
    nextService: '2026-01-05',
    mileage: 267000,
    driver: 'Pedro Gomez',
    alerts: [
      {
        id: 'a2',
        vehicleId: '3',
        type: 'Motor',
        message: 'Temperatura elevada del motor detectada',
        severity: 'critical',
        timestamp: '2026-01-30T08:15:00',
        isRead: false,
      },
      {
        id: 'a3',
        vehicleId: '3',
        type: 'Aceite',
        message: 'Nivel de aceite bajo - requiere atencion inmediata',
        severity: 'high',
        timestamp: '2026-01-29T14:20:00',
        isRead: false,
      },
    ],
  },
  {
    id: '4',
    plate: 'MN 012 OP',
    brand: 'Iveco',
    model: 'Stralis 480',
    year: 2022,
    status: 'in_workshop',
    health: 45,
    lastService: '2025-12-01',
    nextService: '2026-03-01',
    mileage: 89000,
    driver: 'Luis Rodriguez',
    alerts: [
      {
        id: 'a4',
        vehicleId: '4',
        type: 'Transmision',
        message: 'En reparacion - cambio de embrague',
        severity: 'medium',
        timestamp: '2026-01-25T09:00:00',
        isRead: true,
      },
    ],
  },
  {
    id: '5',
    plate: 'QR 345 ST',
    brand: 'MAN',
    model: 'TGX 18.500',
    year: 2023,
    status: 'operational',
    health: 98,
    lastService: '2026-01-10',
    nextService: '2026-04-10',
    mileage: 42000,
    driver: 'Diego Martinez',
    alerts: [],
  },
  {
    id: '6',
    plate: 'UV 678 WX',
    brand: 'DAF',
    model: 'XF 530',
    year: 2020,
    status: 'operational',
    health: 85,
    lastService: '2025-12-20',
    nextService: '2026-03-20',
    mileage: 178000,
    driver: 'Andres Lopez',
    alerts: [],
  },
]

export const mockServiceHistory: ServiceHistory[] = [
  {
    id: 'sh1',
    vehicleId: '1',
    date: '2025-12-15',
    type: 'Mantenimiento preventivo',
    description: 'Cambio de aceite, filtros y revision general',
    cost: 125000,
    workshop: 'Taller AutoCam',
    mechanic: 'Miguel Torres',
  },
  {
    id: 'sh2',
    vehicleId: '1',
    date: '2025-09-10',
    type: 'Frenos',
    description: 'Cambio de pastillas delanteras',
    cost: 85000,
    workshop: 'Taller AutoCam',
    mechanic: 'Miguel Torres',
  },
  {
    id: 'sh3',
    vehicleId: '2',
    date: '2025-11-20',
    type: 'Mantenimiento preventivo',
    description: 'Service completo 200.000 km',
    cost: 280000,
    workshop: 'Taller AutoCam',
    mechanic: 'Carlos Ruiz',
  },
  {
    id: 'sh4',
    vehicleId: '3',
    date: '2025-10-05',
    type: 'Reparacion',
    description: 'Cambio de turbo y revision de inyectores',
    cost: 450000,
    workshop: 'Taller AutoCam',
    mechanic: 'Miguel Torres',
  },
  {
    id: 'sh5',
    vehicleId: '4',
    date: '2025-12-01',
    type: 'Mantenimiento preventivo',
    description: 'Cambio de aceite y filtros',
    cost: 95000,
    workshop: 'Taller AutoCam',
    mechanic: 'Carlos Ruiz',
  },
]

export const mockNotifications: Notification[] = [
  {
    id: 'n1',
    title: 'Alerta Critica',
    message: 'Volvo FH16 750 (IJ 789 KL) - Temperatura del motor elevada',
    type: 'alert',
    timestamp: '2026-01-30T08:15:00',
    isRead: false,
    vehicleId: '3',
  },
  {
    id: 'n2',
    title: 'Vehiculo en Taller',
    message: 'Iveco Stralis 480 (MN 012 OP) ingreso al taller para reparacion',
    type: 'info',
    timestamp: '2026-01-25T09:00:00',
    isRead: true,
    vehicleId: '4',
  },
  {
    id: 'n3',
    title: 'Service Completado',
    message: 'Mercedes-Benz Actros 2546 (AB 123 CD) - Mantenimiento completado',
    type: 'success',
    timestamp: '2025-12-15T16:30:00',
    isRead: true,
    vehicleId: '1',
  },
  {
    id: 'n4',
    title: 'Recordatorio',
    message: 'Scania R500 (EF 456 GH) - Service programado en 20 dias',
    type: 'warning',
    timestamp: '2026-01-28T10:00:00',
    isRead: false,
    vehicleId: '2',
  },
  {
    id: 'n5',
    title: 'Alerta de Desgaste',
    message: 'Scania R500 (EF 456 GH) - Desgaste de pastillas de freno detectado',
    type: 'warning',
    timestamp: '2026-01-28T10:30:00',
    isRead: false,
    vehicleId: '2',
  },
]

export const fleetStats = {
  totalVehicles: 6,
  operational: 3,
  attention: 1,
  critical: 1,
  inWorkshop: 1,
  averageHealth: 71,
  totalAlerts: 4,
  pendingServices: 2,
  monthlyMaintenance: 485000,
  yearlyMaintenance: 3250000,
}

export const workshopStats = {
  vehiclesInShop: 3,
  pendingDiagnostics: 2,
  completedToday: 1,
  weeklyRevenue: 1250000,
  avgRepairTime: '2.5 dias',
  customerSatisfaction: 4.8,
}
